#+TITLE:  CSE216 : Programming Abstractions (State University of New York, Korea, Spring 2023)
#+HTML_HEAD_EXTRA: <style>span[class^="section-number-"]:after { content: '.'; }</style>



* Course overview
This course is  offered by the CS Department of SUNY Korea. In this course, we will learn
Intermediate-level programming concepts and paradigms, including functional programming, object-orientation, basics of type systems, memory management, program and data abstractions, parameter passing, modularity, version control, and parallel programming.


This repository is publicly accessible and hosts  courseware that will be incrementally added along the semester.  We will adapt the courseware from the ones used at Stony Brook University.

* Course objectives
- An understanding of programming paradigms and tradeoffs.

- An understanding of functional techniques to identify, formulate and solve problems.

- An ability to apply techniques of object-oriented programming in the context of software development.



* Prerequisites
C or higher in CSE 214; CSE major

* Reference Book(s) and additional reading

There is no single textbook for this course, but we will mostly be covering conceptual material from

Scott, Michael L., Programming Language Pragmatics. Morgan Kaufmann; 3rd Edition (2009).

For details pertaining to specific programming languages, the recommended material will mostly be from the following:

Python tutorial: https://docs.python.org/3/tutorial/

OCaml learning material: https://ocaml.org/learn/


* Schedule 

Lectures: Monday and Wednesday 2:00 - 3:20pm, at B203 

Recitation: Wednesday 3:30 - 4:25pm, at B203

Office hours: Monday  5:00 - 6:00pm  and Wednesday 8:00 - 9:00pm, at B424

Midterm exams: TBA

Final exam: Monday, June 12, 12:30-3:00pm.  

TA office hours: TBA


Zoom just in case:
https://stonybrook.zoom.us/j/99671076796?pwd=TGFuZ1lzSXpnSWlpMDB2a2tCRmozUT09


Overall Schedule:

- Programming paradigms
  
-  Lambda calculus 

- Functional programming with OCaml

- Midterm 1
    
- Types and type systems

- ... TBA

- Final exam


Detailed Schedule to be updated on a weeekly

Week01 (23-02-27)
- Monday: Course Overview
- Wednesday:  No class






    


* Grading
- Attendance: 5%
- take-home assignment: 25%
- In-class assignment: 10%  
- Midterms: 30%
- Final exam: 30%


Late homework will generally not be accepted. Special requests must be presented to the course instructor with all supporting documentation as soon as possible. Once the solutions to the homework exercises are publicized, there shall be no ways to accept assignments, whatever the circumstance. 



* Instructor 
Zhoulai Fu <zhoulai dot fu at sunykorea.ac.kr>  or  <zhoulai dot fu at stonybrook.edu>


* Teaching assistant
TBA 



* Disability Support Services (DSS) Statement

If you have a physical, psychological, medical or learning disability that may impact your course work, please contact  One-Stop Service Center, Academic Building A201, (82) 32-626-1117. They will determine with you what accommodations, if any, are necessary and appropriate. All information and documentation is confidential.

 Students who require assistance during emergency evacuation are encouraged to discuss their needs with instructors and the One-Stop Service Center.
 
 
* Academic integrity

Each student must pursue his or her academic goals honestly and be personally accountable for all submitted work. Representing another person's work as your own is always wrong. Faculty members are required to report any suspected instances of academic dishonesty to the Academic Judiciary Committee or the Department of Academic Affairs, Campus Building A, Room 201, (032) 626-1121.

* Critical incident management

SUNY Korea expects students to respect the rights,
privileges, and property of other people. Faculty are required to report to the Department of Academic Affairs any disruptive behavior that interrupts their ability to teach, compromises the safety of the learning environment, or inhibits students' ability to learn.
